import "./globals.css";
import StravaRedirectHandler from "./components/StravaRedirectHandler";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <StravaRedirectHandler />

      <body>{children}</body>
    </html>
  );
}
